# Chapter 7

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
float_data = pd.Series([1.2,-3.5,np.nan,0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

isna returns a Boolean Series with True where values are Null

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data= pd.Series(["aardvark",np.nan,None,"avacodo"])

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype='float64')


In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
string_data

0    aardvark
1         NaN
2        None
3     avacodo
dtype: object

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

to get rid of missing values you can use:

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])


In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

how="all" will drop only rows that are all NA

In [18]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = np.nan

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [23]:
df.iloc[:4,1]= np.nan

In [24]:
df.iloc[:2,2]= np.nan

In [25]:
df

0         1         2
0 -0.839095       NaN       NaN
1 -0.538858       NaN       NaN
2  0.188270       NaN -2.191722
3  0.259722       NaN  0.774642
4 -0.854378  0.260870  1.289421
5 -2.500724 -0.990015 -1.849795
6 -0.216282  0.676777  0.993059

In [26]:
df.dropna()

0         1         2
4 -0.854378  0.260870  1.289421
5 -2.500724 -0.990015 -1.849795
6 -0.216282  0.676777  0.993059

In [27]:
df.dropna(thresh=2)

0         1         2
2  0.188270       NaN -2.191722
3  0.259722       NaN  0.774642
4 -0.854378  0.260870  1.289421
5 -2.500724 -0.990015 -1.849795
6 -0.216282  0.676777  0.993059

you can fill NA values with fillna

In [28]:
df

0         1         2
0 -0.839095       NaN       NaN
1 -0.538858       NaN       NaN
2  0.188270       NaN -2.191722
3  0.259722       NaN  0.774642
4 -0.854378  0.260870  1.289421
5 -2.500724 -0.990015 -1.849795
6 -0.216282  0.676777  0.993059

In [29]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.839095  0.500000  0.000000
1 -0.538858  0.500000  0.000000
2  0.188270  0.500000 -2.191722
3  0.259722  0.500000  0.774642
4 -0.854378  0.260870  1.289421
5 -2.500724 -0.990015 -1.849795
6 -0.216282  0.676777  0.993059

In [30]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [31]:
df.iloc[2:,1] = np.nan

In [32]:
df.iloc[4:,2] = np.nan

In [33]:
df

0         1         2
0  0.023341 -0.226947 -1.026309
1  0.307534 -0.757571 -0.645667
2 -1.754014       NaN -1.287258
3  0.762399       NaN -0.912834
4 -0.720885       NaN       NaN
5  0.659164       NaN       NaN

In [34]:
df.fillna(method="ffill")

/var/folders/y_/88_bvhts341bf74krgd3hgch0000gp/T/ipykernel_8481/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.023341 -0.226947 -1.026309
1  0.307534 -0.757571 -0.645667
2 -1.754014 -0.757571 -1.287258
3  0.762399 -0.757571 -0.912834
4 -0.720885 -0.757571 -0.912834
5  0.659164 -0.757571 -0.912834

In [35]:
df.fillna(method="ffill", limit=2)


/var/folders/y_/88_bvhts341bf74krgd3hgch0000gp/T/ipykernel_8481/3889071623.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.023341 -0.226947 -1.026309
1  0.307534 -0.757571 -0.645667
2 -1.754014 -0.757571 -1.287258
3  0.762399 -0.757571 -0.912834
4 -0.720885       NaN -0.912834
5  0.659164       NaN -0.912834

In [36]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

in the  next example we fill the NA vaslues with the mean

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

find the duplicates with

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

and get rid of them with

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data["v1"] = range(7)

you can specify clumns with 

In [43]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
        "pastrami", "corned beef", "bacon",
        "pastrami", "honey ham", "nova lox"],
        "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [46]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

you can use the map funcrtion to add these values to the df. accepts dictionary format

In [48]:
data["animal"] = data["food"].map(meat_to_animal)

In [49]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [50]:
def get_animal(x):
    return meat_to_animal[x]

In [51]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [52]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [53]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [54]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

to replace multiple values use

In [56]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

to replace each other those selected values use: 

In [57]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

The argument passed can also be a dictionary:

In [58]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [60]:
def transform(x):
    return x[:4].upper()

In [61]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [62]:
data.index = data.index.map(transform)

In [63]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

If you want to create a transformed version of a dataset without modifying the original, a useful method is rename:

In [64]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [65]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [66]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [67]:
bins = [18, 25, 35, 60, 100]

In [68]:
age_categories = pd.cut(ages,bins)

In [69]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [70]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [71]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [72]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [73]:
pd.value_counts(age_categories)

/var/folders/y_/88_bvhts341bf74krgd3hgch0000gp/T/ipykernel_8481/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [74]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [75]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [76]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [77]:
data = np.random.uniform(size=20)

In [78]:
pd.cut(data, 4, precision=2)

[(0.66, 0.88], (0.44, 0.66], (0.0035, 0.22], (0.22, 0.44], (0.44, 0.66], ..., (0.0035, 0.22], (0.66, 0.88], (0.44, 0.66], (0.0035, 0.22], (0.66, 0.88]]
Length: 20
Categories (4, interval[float64, right]): [(0.0035, 0.22] < (0.22, 0.44] < (0.44, 0.66] < (0.66, 0.88]]

In [79]:
data = np.random.standard_normal(1000)

In [80]:
quartiles = pd.qcut(data,4,precision=2)

In [81]:
quartiles

[(-3.09, -0.69], (-3.09, -0.69], (-0.69, 0.029], (0.62, 3.94], (-3.09, -0.69], ..., (-3.09, -0.69], (0.62, 3.94], (0.029, 0.62], (-3.09, -0.69], (0.029, 0.62]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.09, -0.69] < (-0.69, 0.029] < (0.029, 0.62] < (0.62, 3.94]]

In [82]:
pd.value_counts(quartiles)

/var/folders/y_/88_bvhts341bf74krgd3hgch0000gp/T/ipykernel_8481/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.09, -0.69]    250
(-0.69, 0.029]    250
(0.029, 0.62]     250
(0.62, 3.94]      250
Name: count, dtype: int64

In [83]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.0829999999999997, -1.252]    100
(-1.252, 0.0292]                 400
(0.0292, 1.249]                  400
(1.249, 3.942]                   100
Name: count, dtype: int64

In [84]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [85]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.042254     0.038630    -0.014784     0.027946
std       1.009702     0.992069     0.982506     0.991806
min      -3.365881    -2.834468    -3.406759    -2.550943
25%      -0.681235    -0.587868    -0.716778    -0.629742
50%       0.044158    -0.004864    -0.011016     0.013671
75%       0.736908     0.695647     0.662801     0.681168
max       3.565394     3.307395     2.913145     3.001499

In [86]:
col = data[2]

In [87]:
col[col.abs() > 3]

185   -3.406759
638   -3.319562
Name: 2, dtype: float64

In [88]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
36  -0.814184 -0.820257  0.348288  3.001499
83   3.549655 -0.179256  0.134157 -0.512680
97  -0.843538  3.242231  0.217237  1.617044
185  1.084136  0.780660 -3.406759  1.204460
385  3.565394  0.238356 -0.044821 -0.469369
415  0.513996  3.307395 -1.819038 -0.452758
638  1.760393 -0.207493 -3.319562  0.377526
874 -3.365881 -0.413368  0.776013  0.621492

In [89]:
data[data.abs() > 3] = np.sign(data) * 3

In [90]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.041505     0.038081    -0.014058     0.027944
std       1.004943     0.990348     0.980158     0.991801
min      -3.000000    -2.834468    -3.000000    -2.550943
25%      -0.681235    -0.587868    -0.716778    -0.629742
50%       0.044158    -0.004864    -0.011016     0.013671
75%       0.736908     0.695647     0.662801     0.681168
max       3.000000     3.000000     2.913145     3.000000

In [91]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0 -1.0  1.0 -1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0 -1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

In [92]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [93]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [94]:
sampler = np.random.permutation(5)

In [95]:
sampler

array([4, 0, 3, 1, 2])

In [96]:
df.take(sampler)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [97]:
df.iloc[sampler]

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [98]:
column_sampler = np.random.permutation(7)

In [99]:
column_sampler

array([0, 2, 1, 4, 3, 5, 6])

In [100]:
df.take(column_sampler, axis = "columns")

0   2   1   4   3   5   6
0   0   2   1   4   3   5   6
1   7   9   8  11  10  12  13
2  14  16  15  18  17  19  20
3  21  23  22  25  24  26  27
4  28  30  29  32  31  33  34

In [101]:
df.sample(n=7, axis="columns")

5   3   0   2   6   1   4
0   5   3   0   2   6   1   4
1  12  10   7   9  13   8  11
2  19  17  14  16  20  15  18
3  26  24  21  23  27  22  25
4  33  31  28  30  34  29  32

this allows you to take a random subeset with out replacement


to allow replacements use this instead

In [102]:
choices = pd.Series([5,7,-1,6,4])

In [103]:
choices.sample(n=10, replace= True)

4    4
4    4
1    7
4    4
0    5
4    4
4    4
1    7
2   -1
3    6
dtype: int64

Computing Indicator/Dummy Variables

In [104]:
df = pd.DataFrame({"key": ["b","b","a","c","a","b"],
                  "data1": range(6)})

In [105]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [106]:
pd.get_dummies(df["key"], dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

dtype is passed here to change the output type from the default boolean to float instead 

to add a prefix to the columns use: 

In [107]:
dummies = pd.get_dummies(df["key"], prefix ="key", dtype=float)

In [108]:
dummies

key_a  key_b  key_c
0    0.0    1.0    0.0
1    0.0    1.0    0.0
2    1.0    0.0    0.0
3    0.0    0.0    1.0
4    1.0    0.0    0.0
5    0.0    1.0    0.0

then you can merge with other data

In [109]:
df_with_dummy = df[["data1"]].join(dummies)

In [110]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [111]:
mnames =  ["movie_id", "title", "genres"]

In [112]:
movies = pd.read_table("datasets/movielens/movies.dat", sep = "::", header = None, names=mnames, engine="python")

In [113]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

to get dummies with rows that fall into multiple categories use

In [114]:
dummies = movies["genres"].str.get_dummies("|")

In [115]:
dummies.iloc[:10,:6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [116]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [117]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [118]:
np.random.seed(12345) # to make the example repeatable

In [119]:
values = np.random.uniform(size=10)

In [120]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [121]:
bins= [0,0.2,0.4,0.6,0.8,1]

In [122]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [123]:
s = pd.Series([1,2,3,None])

In [124]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [125]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

you can change the type of your missing value with:

In [126]:
s = pd.Series([1,2,3,None], dtype=pd.Int64Dtype())

In [127]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [128]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [129]:
s.dtype

Int64Dtype()

In [130]:
s[3]

<NA>

In [131]:
s[3] is pd.NA

True

you can use shorthand for the type change:

In [132]:
s = pd.Series([1,2,3,None], dtype = "Int64")

In [133]:
s = pd.Series(['one','two',None,'three'], dtype=pd.StringDtype())

In [134]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [135]:
df = pd.DataFrame({"A": [1, 2, None, 4],
        "B": ["one", "two", "three", None],
        "C": [False, None, False, True]})

In [136]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [137]:
df["A"]= df["A"].astype("Int64")

In [138]:
df["B"]= df["B"].astype("string")

In [139]:
df["C"]= df["C"].astype("boolean")

In [140]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

in this example we use the built-in String object methods split()
and strip to turn comma separated values in to a list while getting rid of extra whitespace. 

In [141]:
val = "a,b,  guido"

In [142]:
pieces = [x.strip() for x in val.split(",")]

In [143]:
pieces

['a', 'b', 'guido']

In [144]:
"::".join(pieces)

'a::b::guido'

In [145]:
"guido" in val

True

In [146]:
val.index(",")

1

In [147]:
val.find(":")

-1

In [148]:
import re

In [149]:
text = "foo    bar\t baz   \tqux"

In [150]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

you can compile a regex for later use with

In [151]:
regex = re.compile(r"\s+")

this creates the regex object so you can call methods on it later

In [152]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [153]:
regex.findall(text)

['    ', '\t ', '   \t']

In [154]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [155]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [156]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

the example below finds the first email address

In [157]:
m = regex.search(text)

In [158]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [159]:
text[m.start():m.end()]

'dave@google.com'

.match() only matches if the pattern is in the beggining of the start of the string

In [160]:
print(regex.match(text))

None


.sub() will return a string of your choosing instead of the pattern

In [161]:
print(regex.sub("REDACTED",text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [162]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [163]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [164]:
m = regex.match("first@second.thrd")

In [165]:
m.groups()

('first', 'second', 'thrd')

In [166]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [167]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))


Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [168]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}


In [169]:
data =pd.Series(data)

In [170]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [171]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [172]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [173]:
data_as_string_ext = data.astype('string')

In [174]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [175]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

With extension types, regular expressions can be used, too, along with any re options like IGNORECASE:

In [176]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [177]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [178]:
 matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [179]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [180]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

you can also slice them

In [181]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [182]:
data.str.extract(pattern,flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

#                                Categorical Data

    Background and Motivation

In [183]:
values = pd.Series(['apple', 'orange', 'apple',
        'apple'] * 2)

In [184]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [185]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [186]:
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [188]:
values = pd.Series([0,1,0,0]*2)

In [189]:
dim = pd.Series(['apple','oranges'])

In [190]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [191]:
dim

0      apple
1    oranges
dtype: object

In [192]:
dim.take(values)

0      apple
1    oranges
0      apple
0      apple
0      apple
1    oranges
0      apple
0      apple
dtype: object

# Categorical Extension Type in pandas

this special type to uses integer-based categorical representation or encoding.

In [193]:
fruits = ['apple','orange','apple','apple'] * 2 

In [194]:
N = len(fruits)

In [195]:
rng = np.random.default_rng(seed=12345)

In [196]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])

In [197]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [198]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [199]:
fruit_cat = df['fruit'].astype('category')

In [200]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [201]:
c = fruit_cat.array

In [202]:
type(c)

pandas.core.arrays.categorical.Categorical

In [204]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [205]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [206]:
dict(enumerate(c.categories))


{0: 'apple', 1: 'orange'}

you can use as type with this extension type as well 

In [208]:
df['fruit'] = df['fruit'].astype('category')

In [209]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

You can also create pandas.Categorical directly from other types of Python sequences:

In [211]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [212]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [213]:
categories = ['foo','bar','baz']

In [214]:
codes = [0,1,2,0,0,1]

In [219]:
my_cats_2 = pd.Categorical.from_codes(codes,categories)

In [220]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [223]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)


In [224]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [225]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

# Computations with Categoricals

In [227]:
rng = np.random.default_rng(seed=12345)

In [228]:
draws = rng.standard_normal(1000)

In [229]:
draws[:]

array([-1.42382504e+00,  1.26372846e+00, -8.70661738e-01, -2.59173235e-01,
       -7.53433070e-02, -7.40884652e-01, -1.36779270e+00,  6.48892802e-01,
        3.61058113e-01, -1.95286306e+00,  2.34740965e+00,  9.68496906e-01,
       -7.59387180e-01,  9.02198274e-01, -4.66953173e-01, -6.06895187e-02,
        7.88844345e-01, -1.25666813e+00,  5.75857514e-01,  1.39897899e+00,
        1.32229806e+00, -2.99698515e-01,  9.02919341e-01, -1.62158273e+00,
       -1.58189261e-01,  4.49483932e-01, -1.34360107e+00, -8.16875907e-02,
        1.72473993e+00,  2.61815943e+00,  7.77361344e-01,  8.28633196e-01,
       -9.58988313e-01, -1.20938829e+00, -1.41229201e+00,  5.41546830e-01,
        7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  

In [231]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [234]:
bins = pd.qcut(draws,4)

In [235]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [238]:
bins = pd.qcut(draws, 4, labels=['Q1','Q2','Q3','Q4']) 

In [239]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [240]:
bins = pd.Series(bins, name='quartile')

In [251]:
results = (pd.Series(draws)
          .groupby(bins, observed=False)
          .agg(['count','min','max'])
          .reset_index())            

In [252]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

# Better performance with categoricals 

In [254]:
N = 10_000_000

In [255]:
labels = pd.Series(['foo','bar','baz','qux'] * (N//4))

now we convert labels to categorical

In [256]:
categories = labels.astype('category')

In [257]:
labels.memory_usage(deep=True)

520000132

In [258]:
categories.memory_usage(deep=True)

10000512

although the conversion itself is not free either, it is a one time cost

In [260]:
%time _ = labels.astype('category')

CPU times: user 167 ms, sys: 57.2 ms, total: 225 ms
Wall time: 252 ms


In [261]:
%timeit labels.value_counts()

176 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [263]:
%timeit categories.value_counts()

17.6 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


#  Categorical Methods

In [264]:
s = pd.Series(['a','b','c','d'] * 2)

In [265]:
cat_s = s.astype('category')

In [266]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [269]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

if the data extends the scope or capacity of these 4 categories we can edit them or add more with this:

In [270]:
actual_categories = ['a','b','c','d','e']

In [272]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [273]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [274]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [277]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [278]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [279]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [280]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [281]:
When you're using statistics or machine learning tools, you'll often transform categorical data into dummy variables, also known as one-hot encoding. This involves creating a DataFrame with a column for each distinct category; these columns contain 1s for occurrences of a given category and 0 otherwise.

Consider the previous example:

SyntaxError: invalid decimal literal (2185497853.py, line 1)